openapi: 3.0.0
info:
  title: User API
  description: A simple API to manage users
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server
paths:

  /device/{subject}:
    get:
      tags:
        - device
      summary: Get device info
      description: Retrieve information about a specific device (Id or name)
      parameters:
        - name: subject
          in: path
          required: true
          schema:
            type: string
          description: Id or name
      responses:
        '200':
          description: Device found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "device123"
                      name:
                        type: string
                        example: "Temperature Sensor"
                      feed:
                        type: string
                        example: "feed123"
                      description:
                        type: string
                        example: "Measures room temperature"
                      power: 
                        type: number
                        example: 100
                      status: 
                        type: boolean
                        example: true 
        '404':
          description: Device not found
        '500':
          description: Internal server error
  
  /device:
    get:
      tags:
        - device
      summary: Get all devices info
      description: Retrieve information about all devices
      responses:
        '200':
          description: Devices found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "device123"
                        name:
                          type: string
                          example: "Temperature Sensor"
                        feed:
                          type: string
                          example: "feed123"
                        description:
                          type: string
                          example: "Measures room temperature"
                        power: 
                          type: number
                          example: 100
                        status: 
                          type: boolean
                          example: true 
        '404':
          description: Devices not found
        '500':
          description: Internal server error

    post:
        tags:
          - device
        summary: Create a new device
        description: Add a new device to the system
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "device123"
                  name:
                    type: string
                    example: "Temperature Sensor"
                  feed:
                    type: string
                    example: "feed123"
                  description:
                    type: string
                    example: "Measures room temperature"
        responses:
          '200':
            description: Device created successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: boolean
                      example: true
                    message:
                      type: string
                      example: "Device created successfully"
          '409':
            description: Device's Id (or name) already exists
          '500':
            description: Internal server error

  /device/config/{subject}:
    get:
      tags:
        - device
      summary: Get all configurations by subject (deviceId)
      description: Retrieve all configurations associated with a specific device using its identifier.
      parameters:
        - name: subject
          in: path
          required: true
          schema:
            type: string
          description: The device identifier.
      responses:
        '200':
          description: Configurations found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: "Room Temperature Control"
                        description:
                          type: string
                          example: "Config for temperature automation"
                        action:
                          type: boolean
                          example: true
                        deviceId:
                          type: string
                          example: "device123"
                        schedulerConfig:
                          type: object
                          nullable: true
                          properties:
                            id:
                              type: integer
                              example: 1
                            start:
                              type: string
                              example: "08:00"
                            end:
                              type: string
                              example: "18:00"
                            repetition:
                              type: string
                              nullable: true
                              example: "daily"
                        automationConfig:
                          type: object
                          nullable: true
                          properties:
                            id:
                              type: integer
                              example: 2
                            conditions:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                    example: 10
                                  condition:
                                    type: string
                                    example: ">50"
        '404':
          description: Configurations not found
        '500':
          description: Internal server error

  /device/config:
    post:
      tags:
          - device
      summary: Create a new configuration
      description: Add a new configuration to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Room Temperature Control"
                description:
                  type: string
                  example: "Config for temperature automation"
                deviceId:
                  type: string
                  example: "device123"
      responses:
        '200':
          description: Configuration created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Config created successfully"
        '409':
          description: Device has been configured before
        '500':
          description: Internal server error

  /device/config/scheduler:
    post:
      tags:
          - device
      summary: Create a scheduler configuration
      description: Add a new scheduler config to a configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configId:
                  type: string
                  example: "config123"
                start:
                  type: string
                  format: date-time
                  example: "2024-03-10T10:00:00Z"
                end:
                  type: string
                  format: date-time
                  example: "2024-03-10T12:00:00Z"
                repetition:
                  type: string
                  example: "daily"
      responses:
        '200':
          description: Scheduler configuration created successfully
        '500':
          description: Internal server error

  /device/config/automation:
    post:
      tags:
          - device
      summary: Create an automation configuration
      description: Add an automation setting to a configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configId:
                  type: string
                  example: "config123"
      responses:
        '200':
          description: Automation configuration created successfully
        '500':
          description: Internal server error

  /device/config/automation/condition:
    post:
      tags:
          - device
      summary: Create an automation condition
      description: Add a condition to an automation configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                configId:
                  type: string
                  example: "config123"
                condition:
                  type: string
                  example: "temperature > 25"
      responses:
        '200':
          description: Condition created successfully
        '500':
          description: Internal server error