openapi: 3.0.0
info:
  title: Notification API
  description: API for retrieving monitoring notifications
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: notification
    description: Endpoints related users's notifications
paths:
  /notification/all:
    get:
      tags:
        - notification
      summary: Get all notifications
      description: Retrieve all monitoring notifications along with their associated monitor details.
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Page number (1-100)
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Number of items per page (1-100)
      responses:
        "200":
          description: A list of notifications
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date-time
                          example: "2023-10-01T10:00:00.000Z"
                        value:
                          type: number
                          example: 90
                        monitor:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: "Temperature"
                            description:
                              type: string
                              example: "Measures the ambient temperature in degrees Celsius"
                            upperbound:
                              type: number
                              example: 100
                            lowerbound:
                              type: number
                              example: 
