openapi: 3.0.0
info:
  title: Notification API
  description: API for retrieving monitoring notifications
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: notification
    description: Endpoints related users's notifications

paths:
  /notification/all:
    get:
      tags:
        - notification
      summary: Retrieve all notifications
      description: Retrieves a list of all notifications for the user.
      parameters:
        - name: page
          in: query
          description: The page number to retrieve (1 to 100)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 1
        - name: pageSize
          in: query
          description: The number of notifications per page (1 to 100)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Successfully retrieved notifications
          content:
            application/json:
              examples:
                SuccessExample:
                  value:
                    status: true
                    data:
                      - id: 22
                        date: "2025-04-09T00:00:38.338Z"
                        description: "test alert send mail"
                        lowerbound: 0
                        upperbound: 5
                        unit: "%"
                        value: 15
                        name: "nhiet do"


  /notification/poll:
    get:
      tags:
        - notification
      summary: Poll for notifications
      description: >
        Checks for notifications. Calls the Polling API when the user is active to retrieve notifications, with each polling request returning only one notification.
        - If there is data: `status` = true and the information is returned in `data`.
        - If there is no data: `status` = false and `data` is set to `null`.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              examples:
                SuccessExample:
                  value:
                    status: true
                    data:
                      id: 22
                      date: "2025-04-09T00:00:38.338Z"
                      description: "test alert send mail"
                      lowerbound: 0
                      upperbound: 5
                      unit: "%"
                      value: 15
                      name: "nhiet do"
                FailureExample:
                  value:
                    status: false
                    data: null


  /notification/status/{id}:
    patch:
      tags:
        - notification
      summary: Update notification status
      description: Updates the read/unread status of a notification
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 22
          description: The ID of the notification to update
      requestBody:
        required: true
        content:
          application/json:
            examples:
              MarkAsRead:
                value:
                  value: true
              MarkAsUnread:
                value:
                  value: false
      responses:
        '200':
          description: Status updated successfully
          content:
            application/json:
              examples:
                SuccessExample:
                  value:
                    status: true
                    message: "Notification status updated successfully"
                FailureExample:
                  value:
                    status: false
                    message: "Failed to update notification status"