openapi: 3.0.0
info:
  title: User API
  description: A simple API to manage users
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server
paths:
  /test:
    get:
      summary: Get a list of users
      description: Retrieve an array of user objects
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: John Doe
    