name: test SSH EC2 
run-name: ${{ github.actor }} is trying to SSH to EC2

on: 
    push:
        branches: [release]

jobs: 
    push-images-to-server: 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout repository 
              uses: actions/checkout@v3
            
            - name: create .env
              env: 
                ENV: ${{ secrets.ENV }} 
              run: echo "$ENV" > .env

            - name: login dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: build docker image 
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/green . 
            
            - name: push docker hub 
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/green

            - name: create pem file 
              env:
                EC2_PEM_KEY: ${{ secrets.EC2_PEM_KEY }} 
              run: | 
                echo "$EC2_PEM_KEY" | base64 -d > my-server.pem
                chmod 400 my-server.pem
                
            - name: ssh to server 
              run: | 
                ssh -o StrictHostKeyChecking=no -i "my-server.pem" ${{ secrets.SERVER_URL }} << EOF
                  echo "CONNECT SUCCESSFULLY"
                  cd /home/ubuntu
                  sudo docker stop $(sudo docker ps -q)
                  echo "REMOVE CONTAINER SUCCESSFULLY"
                  sudo sudo docker rm -f $(sudo docker ps -aq)
                  sudo docker rmi -f $(sudo docker images -q)
                  echo "REMOVE ALL IMAGES SUCCESSFULLY"
                  sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/green
                  echo "PULL IMAGE SUCCESSFULLY"
                  sudo docker run -dp 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/green
                EOF
              